name: CI-Pipeline

# Controls when the workflow will run, when comment is created
on:
  issue_comment:
    types:
      - created
jobs:
  call-terraform-ci-pipeline:
    uses: terraform-ibm-modules/common-pipeline-assets/.github/workflows/common-terraform-module-ci-v2.yml@v1.17.0
    secrets: inherit
    with:
      craSCCv2: true
      craTarget: "ibm-catalog/fscloud"
      craRuleIgnoreFile: "cra-tf-validate-ignore-rules.json"
      craEnvironmentVariables: 'TF_VAR_allowed_ip_addresses=[\"17.5.7.8.0/16\"]'
